name: Build-PSModule
description: Build a PowerShell module to the PowerShell Gallery.
author: PSModule

inputs:
  Name:
    description: Name of the module to process.
    required: false
  ArtifactName:
    description: Name of the artifact to upload.
    required: false
    default: module
  WorkingDirectory:
    description: The working directory where the script will run from.
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: Install-PSModuleHelpers
      uses: PSModule/Install-PSModuleHelpers@d60d63e4be477d1ca0c67c6085101fb109bce8f1 # v1.0.6

    - name: Run Build-PSModule
      shell: pwsh
      id: build
      working-directory: ${{ inputs.WorkingDirectory }}
      env:
        PSMODULE_BUILD_PSMODULE_INPUT_Name: ${{ inputs.Name }}
      run: |
        # Build-PSModule
        ${{ github.action_path }}/src/main.ps1

    - name: Upload module artifact
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: ${{ inputs.ArtifactName }}
        path: ${{ steps.build.outputs.ModuleOutputFolderPath }}
        if-no-files-found: error
        retention-days: 1
