name: Build-PSModule (by PSModule)
description: Build a PowerShell module to the PowerShell Gallery.
author: PSModule
branding:
  icon: package
  color: gray-dark

inputs:
  Name:
    description: Name of the module to process.
    required: false
  ArtifactName:
    description: Name of the artifact to upload.
    required: false
    default: module
  Debug:
    description: Enable debug output.
    required: false
    default: 'false'
  Verbose:
    description: Enable verbose output.
    required: false
    default: 'false'
  Version:
    description: Specifies the version of the GitHub module to be installed. The value must be an exact version.
    required: false
  Prerelease:
    description: Allow prerelease versions if available.
    required: false
    default: 'false'
  WorkingDirectory:
    description: The working directory where the script will run from.
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: Install-PSModuleHelpers
      uses: PSModule/Install-PSModuleHelpers@removeInit

    - name: Run Build-PSModule
      uses: PSModule/GitHub-Script@v1
      id: build
      env:
        PSMODULE_BUILD_PSMODULE_INPUT_Name: ${{ inputs.Name }}
      with:
        Debug: ${{ inputs.Debug }}
        Prerelease: ${{ inputs.Prerelease }}
        Verbose: ${{ inputs.Verbose }}
        Version: ${{ inputs.Version }}
        WorkingDirectory: ${{ inputs.WorkingDirectory }}
        Script: |
          # Build-PSModule
          ${{ github.action_path }}/scripts/main.ps1

    - name: Upload module artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.ArtifactName }}
        path: ${{ fromJson(steps.build.outputs.result).moduleOutputFolderPath }}
        if-no-files-found: error
        retention-days: 1
