name: Build-PSModule
description: Build a PowerShell module to the PowerShell Gallery
branding:
  icon: activity
  color: blue

inputs:
  Verbose:
    description: Enable verbose output.
    required: false
    default: 'true'
  WhatIf:
    description: Run in WhatIf mode.
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Run Build-PSModule
      shell: pwsh
      env:
        Verbose: ${{ inputs.Verbose }}
        WhatIf: ${{ inputs.WhatIf }}
      run: . "$env:GITHUB_ACTION_PATH\scripts\main.ps1"
