name: Build-PSModule
description: Build a PowerShell module to the PowerShell Gallery.
author: PSModule

inputs:
  Name:
    description: Name of the module to process.
    required: false
  ArtifactName:
    description: Name of the artifact to upload.
    required: false
    default: module
  WorkingDirectory:
    description: The working directory where the script will run from.
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: Install-PSModuleHelpers
      uses: PSModule/Install-PSModuleHelpers@v1

    - name: Run Build-PSModule
      shell: pwsh
      id: build
      working-directory: ${{ inputs.WorkingDirectory }}
      env:
        PSMODULE_BUILD_PSMODULE_INPUT_Name: ${{ inputs.Name }}
      run: |
        # Build-PSModule
        ${{ github.action_path }}/scripts/main.ps1

    - name: Upload module artifact
      uses: actions/upload-artifact@v5
      with:
        name: ${{ inputs.ArtifactName }}
        path: ${{ steps.build.outputs.ModuleOutputFolderPath }}
        if-no-files-found: error
        retention-days: 1
