name: 'Build-Module'
description: 'Build a PowerShell module to the PowerShell Gallery'
branding:
  icon: activity
  color: blue

inputs:
  Verbose:
    description: 'Enable verbose output.'
    required: false
    default: 'false'
  WhatIf:
    description: 'Run in WhatIf mode.'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Run Build-Module
      shell: pwsh
      run: |
        # Build-Module
        Write-Output '::group::[Build-Module] - Initializing...'
        Write-Output '-------------------------------------------'
        Write-Output 'Action inputs:'
        $params = @{
            Verbose = [System.Convert]::ToBoolean('${{ inputs.Verbose }}')
            WhatIf  = [System.Convert]::ToBoolean('${{ inputs.WhatIf }}')
        }
        $params.GetEnumerator() | Sort-Object -Property Name

        Write-Output '-------------------------------------------'
        . "$env:GITHUB_ACTION_PATH\scripts\main.ps1" @params
        Write-Output '-------------------------------------------'
        Write-Output '::endgroup::'
